# Generated by Django 5.0.4 on 2024-05-21 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DentalCare', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointmentDate',
            new_name='AppointmentDate',
        ),
    ]
