# Generated by Django 5.0.4 on 2024-05-21 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DentalCare', '0002_rename_appointmentdate_appointment_appointmentdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='description',
        ),
    ]
