# Generated by Django 5.0.4 on 2024-05-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DentalCare', '0004_patient_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
