# Generated by Django 5.0.4 on 2024-05-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DentalCare', '0006_alter_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='patient',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
