# Generated by Django 5.0.4 on 2024-05-28 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DentalCare', '0009_alter_patient_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='AppoitmentsDone',
            new_name='AppointmentsDone',
        ),
    ]
