# Generated by Django 5.0.4 on 2024-05-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DentalCare', '0010_rename_appoitmentsdone_appointment_appointmentsdone'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
