# Generated by Django 5.0.4 on 2024-06-05 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DentalCare', '0011_appointment_is_canceled'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Symptom',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='address',
        ),
    ]
