# Generated by Django 5.0.4 on 2024-06-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DentalCare', '0012_delete_symptom_remove_doctor_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='address_line_1',
            field=models.CharField(default='7/2/B', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='city',
            field=models.CharField(default='Ahmedabad', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='country',
            field=models.CharField(choices=[('UNITED STATES OF AMERICA', 'United States of America'), ('INDIA', 'India'), ('UNITED KINGDOM', 'United Kingdom')], default='India', max_length=50),
        ),
        migrations.AddField(
            model_name='doctor',
            name='dob',
            field=models.DateField(default='2000-02-13'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHERS', 'Others')], default='Male', max_length=50),
        ),
        migrations.AddField(
            model_name='doctor',
            name='postcode',
            field=models.IntegerField(default=380001),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='register_id',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='state',
            field=models.CharField(default='Gujarat', max_length=50),
            preserve_default=False,
        ),
    ]
