# Generated by Django 5.0.4 on 2024-06-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DentalCare', '0013_doctor_address_line_1_doctor_city_doctor_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/PatientProfilePic/'),
        ),
    ]
