# Generated by Django 5.0.4 on 2024-06-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DentalCare', '0014_doctor_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address_line_1',
            field=models.CharField(default='7/2/B', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.CharField(default='Ahmedabad', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='country',
            field=models.CharField(choices=[('UNITED STATES OF AMERICA', 'United States of America'), ('INDIA', 'India'), ('UNITED KINGDOM', 'United Kingdom')], default='India', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='postcode',
            field=models.IntegerField(default=380007),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='state',
            field=models.CharField(default='Gujarat', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
