# Generated by Django 5.0.4 on 2024-06-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DentalCare', '0015_patient_address_line_1_patient_city_patient_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='dob',
            field=models.DateField(default='2003-11-14'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHERS', 'Others')], default='Male', max_length=50),
        ),
    ]
